on: [push]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: a11ytester
        uses: mikaelvesavuori/a11ytester-action@v1
        with:
          urls: '[\"benefits.gov\"]'
      - uses: actions/upload-artifact@v3
        with:
          name: a11y-reports
          path: results/
